set fbc=c:\freebasic\fbc.exe

%fbc% 01_Example_HelloWorld.bas
%fbc% 02_Example_2DImages.bas
%fbc% 03_Example_BitmapFont.bas
%fbc% 04_Example_3DModes.bas
%fbc% 05_Example_BSPMap.bas
%fbc% 06_Example_Billboards.bas
%fbc% 07_Example_ParticleSystem.bas
%fbc% 08_Example_ShadowsAndLights.bas
%fbc% 09_Example_Skybox.bas
%fbc% 10_Example_TerrainAndFog.bas
%fbc% 11_Example_Animators.bas
%fbc% 12_Example_Collision.bas
%fbc% 13_Example_CameraPosition.bas
%fbc% 14_Example_Win32_Window.bas
%fbc% 21_Example_CarryingObjects.bas
%fbc% 23_Example_Video_Features.bas
%fbc% 28_Example_Hillplane.bas
%fbc% 29_Example_Skydome.bas
%fbc% 30_Example_Animated_Water.bas
%fbc% 31_Example_Loading_Scene.bas
%fbc% 32_Example_3D_Drawing.bas
%fbc% 33_Example_Render_to_Texture.bas
%fbc% 36_Example_Simple_Materials.bas
%fbc% 38_Example_Dynamic_Lighting.bas
%fbc% 44_Example_Animating_Joints.bas
%fbc% 46_Example_Spotlight.bas
%fbc% 47_Example_2D_Animation.bas
%fbc% 48_Example_Animated_Billboard.bas
%fbc% 49_Example_Loaded_Scene_Collision.bas
%fbc% 51_Example_Clouds.bas
%fbc% 52_Example_LensFlare.bas
%fbc% 53_Example_Grass.bas
%fbc% 55_Example_Zone_Management.bas
%fbc% 56_Example_Zone_Bounding_Box.bas
%fbc% 57_Example_Node_Name.bas
%fbc% 65_Example_Sphere_Terrain.bas
%fbc% 66_Example_Stop_Particles.bas
%fbc% 67_Example_Push_Particles.bas
%fbc% 68_Example_Color_Particles.bas
%fbc% 74_Example_Push_Particle_Mushroom_Cloud.bas
%fbc% 75_Example_Push_Particle_Explosion.bas
%fbc% 76_Example_Maya_Style_Camera.bas
%fbc% 78_Example_2D_Overlaid_HUD.bas
%fbc% 84_Example_GUI.bas
%fbc% 85_Example_Split_Screen.bas
%fbc% 90_Example_Collision_Node_Point.bas
%fbc% 93_Example_3DPositionFromScreen.bas
%fbc% 94_Example_BumpMapping.bas
%fbc% 98_Example_Batching_Meshes.bas
%fbc% 99_Example_XEffects_Dynamic_Shadows.bas
%fbc% 100_Example_XEffects_Water.bas
%fbc% 102_Example_XEffects_VarianceShadowMap.bas
%fbc% 103_Example_Billboard_Group.bas
%fbc% 105_Example_Billboard_Properties.bas
%fbc% 107_Example_Render_to_texture_with_alpha.bas
%fbc% 108_Example_Bolt_Node.bas
%fbc% 109_Example_Beam_Node.bas
%fbc% 110_Example_Fade_Node_Animators.bas
%fbc% 111_Example_Fade_Animator_for_Transparency.bas
%fbc% 112_Example_3d_effect_music.bas
%fbc% 113_Example_play_music.bas
pause